%DSAA GROUP_20
%ANIRUDH KANNAN
%DHARANI AKURATHI
%MONICA SAGAR
%LAISHA WADHWA

clear
FigWin = figure('Position',[50 -50 650 500],...
   'Name','..',...
   'NumberTitle','off',...
   'Color',[ 0.12346470588235 0.2123478431 0.245369411765 ]);

AxesHandle1 = axes('Position',[0.2 0.15 0.35 0.7],...
   'Box','on');
AxesHandle2 = axes('Position',[0.6 0.15 0.35 0.7],...
   'Box','on');

BackColor = get(gcf,'Color');


FrameBox = uicontrol(FigWin,...
   'Units','normalized', ...
   'Style','frame',...
   'BackgroundColor',[ 0.741176470588235 0.725490196078431 0.658823529411765 ],...
   'ForegroundColor',[ 0.741176470588235 0.725490196078431 0.658823529411765 ],...
	'Position',[0 0 0.15 1]);

%create static text.
Text2 = uicontrol(FigWin,...
   'Style','text',...
   'Units','normalized', ...
   'Position',[0 0.95 1 0.05],...
   'FontSize',15,...
   'BackgroundColor',[  0.827450980392157 0.815686274509804 0.776470588235294 ],...
   'HorizontalAlignment','center', ...
   'String','FINGERPRINT MATCHING DSAA PROJECT');


Text2 = uicontrol(FigWin,...
   'Style','text',...
   'Units','normalized', ...
   'Position',[0 0 1 0.05],...
   'FontSize',15,...
   'BackgroundColor',[  0.827450980392157 0.815686274509804 0.776470588235294 ],...
   'HorizontalAlignment','center', ...
   'String','GROUP 20- ANIRUDH KANNAN , DHARANI AKURATHI , MONICA SAGAR , LAISHA WADHWA');

w=16;
textLoad='Load Fingerprint Image';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[2,500,150,40],...
   'String','LOAD',...
   'Callback',...
   ['image1=loadimage;'...
    'subplot(AxesHandle1);'...
    'imagesc(image1);'...
    'title(textLoad);'...
	 'colormap(gray);']);

text_eq='Enhancement by histogram Equalization';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[2,460,150,40],...
   'String','HIS-EQUALIZATION',...
   'Callback',...
   ['subplot(AxesHandle2);image1=histeq(uint8(image1));imagesc(image1);title(text_eq);']);


text='Please input the FFT factor(0~1)';
text_fft='Enhancement by FFT';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[2,420,150,40],...
   'String','FFT',...
   'Callback',...
   ['W=inputdlg(text);W=str2double(char(W));'...
    'subplot(AxesHandle1);image1=fftenhance(image1,W);imagesc(image1);title(text_fft);']);

text21='Adaptive Binarization after FFT';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[2,380,150,40],...
   'String','BINARIZATION',...
   'Callback',...
   [%'W=inputdlg(text);W=str2num(char(W));'...
      'subplot(AxesHandle1);'...
      'image1=adaptiveThres(double(image1),32);title(text21);']);

text_filterArea='Orientation Flow Estimate';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
	'Position',[2,340,150,40],...   
	'String','DIRECTION',...
	'Callback',...
   ['subplot(AxesHandle2);[o1Bound,o1Area]=direction(image1,16);title(text_filterArea);']);

text_ROI='Region Of Interest(ROI)';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
	'Position',[2,300,150,40],...   
	'String','ROI AREA',...
	'Callback',...
   ['subplot(AxesHandle2);[o2,o1Bound,o1Area]=drawROI(image1,o1Bound,o1Area);title(text_ROI);']);




text31='Thinned-ridge map';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[2,260,150,40],...
   'String','THINING',...
   'Callback',...
   ['subplot(AxesHandle2);o1=im2double(bwmorph(o2,''thin'',Inf));imagesc(o1,[0,1]);title(text31);']);

text41='Remove H breaks';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[2,220,150,40],...
   'String','H BREAKS REMOVAL',...
	'Callback',...
   ['subplot(AxesHandle2);o1=im2double(bwmorph(o1,''clean''));o1=im2double(bwmorph(o1,''hbreak''));imagesc(o1,[0,1]);title(text41);']);


textn1='remove spike';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
   'Position',[2,180,150,40],...
   'String','SPIKE REMOVAL',...
   'Callback',...
   ['subplot(AxesHandle2);o1=im2double(bwmorph(o1,''spur''));imagesc(o1,[0,1]);title(textn1);']);

%% locate minutia and show all those minutia
text51='Minutia';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
	'Position',[2,140,150,40],...   
	'String','EXTRACT MINUTIA',...
	'Callback',...
   ['[end_list1,branch_list1,ridgeMap1,edgeWidth]=mark_minutia(o1,o1Bound,o1Area,w);'...
	'subplot(AxesHandle2);show_minutia(o1,end_list1,branch_list1);title(text51);']);

%Process for removing spurious minutia
text61='Remove spurious minutia';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
	'Position',[2,100,150,40],...
	'String','REAL MINUTIA',...
   'Callback',...
   ['[pathMap1,real_end1,real_branch1]=remove_spurious_Minutia(o1,end_list1,branch_list1,o1Area,ridgeMap1,edgeWidth);'...
   'subplot(AxesHandle1);show_minutia(o1,real_end1,real_branch1);title(text61);']);

%save template file, including the minutia position,direction,and ridge information
textSaveName='file name';
h=uicontrol(FigWin,...
   'Style','pushbutton',...
	'Position',[2,60,150,40],...
	'String','SAVE',...
   'Callback',...
   ['W=inputdlg(textSaveName);W=char(W);'...
    'save(W,''real_end1'',''pathMap1'',''-ASCII'');']);

%invoke template file loader and do matching
h=uicontrol('Style','pushbutton',...
   'String','MATCH',...
	'Position',[2,600,150,40],...
	'Callback',...
   ['finger1=fingerTemplateRead;'...
    'finger2=fingerTemplateRead;'...
    'percent_match=match_end(finger1,finger2,10);']);
